# SPDX-FileCopyrightText: 2026 CESNET z.s.p.o
# SPDX-License-Identifier: MIT

"""Tests for the blueprint factories generated by the blueprint presets."""

from __future__ import annotations

import flask


def test_app_blueprint_mounts_under_model_slug(empty_model):
    """The app blueprint must be mounted under the model's slug."""
    blueprint = empty_model.blueprints.create_app_blueprint(flask.Flask("app-blueprint-test"))

    assert blueprint.name == "test_app"
    assert blueprint.url_prefix.rstrip("/") == "/test"
