"""A module for registering and unregistering OAREPO models into the Python import system."""

#
# Copyright (c) 2025 CESNET z.s.p.o.
#
# This file is a part of oarepo-model (see http://github.com/oarepo/oarepo-model).
#
# oarepo-model is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#
from __future__ import annotations

import importlib.abc
import importlib.machinery
import importlib.metadata
import importlib.resources.abc
import importlib.util
import io
import sys
from importlib.metadata import Distribution, DistributionFinder
from types import ModuleType, SimpleNamespace
from typing import TYPE_CHECKING, Any, Iterator, cast, override

if TYPE_CHECKING:
    from collections.abc import Sequence
    from importlib.metadata._meta import SimplePath

    from .model import InvenioModel


class ModelDistribution(Distribution):
    """A distribution for the in-memory OAREPO model."""

    def __init__(self, model: InvenioModel, namespace: SimpleNamespace):
        """Initialize the ModelDistribution with a model and namespace.

        :param model: The InvenioModel instance.
        :param namespace: The namespace associated with the model containing entry points and files.
        """
        self.model = model
        self.namespace = namespace

    @override
    def read_text(self, filename: str) -> str | None:
        if filename == "METADATA":
            return f"""
Metadata-Version: 2.1
Name: runtime-models-{self.model.name}
Version: {self.model.version}

..
    Copyright (C) 2025 CESNET z.s.p.o.

    This file has been generated by the OAREPO model system.
    """.strip()
        return None

    @override
    def locate_file(
        self,
        path: Any,
    ) -> SimplePath:
        """Model does not have any files to locate."""
        raise NotImplementedError("Not implemented")

    @property
    @override
    def entry_points(self) -> importlib.metadata.EntryPoints:
        return cast("importlib.metadata.EntryPoints", self.namespace.entry_points)

    @property
    @override
    def files(self) -> list:
        ret = []

        # Collect all files
        files_dict = {}
        for file_name, file_content in self.namespace.__files__.items():
            full_path = f"runtime_models_{self.model.name}/{file_name}"
            files_dict[full_path] = file_content

        # Create InMemoryTraversable for each file
        for file_name, file_content in self.namespace.__files__.items():
            full_path = f"runtime_models_{self.model.name}/{file_name}"
            ret.append(
                InMemoryTraversable(full_path, files_dict, is_dir=False),
            )

        return ret


class InMemoryTraversable(importlib.resources.abc.Traversable):
    def __init__(self, name: str, files_dict: dict[str, str], is_dir: bool = False):
        """Initialize the traversable with name, files dictionary, and directory flag."""
        self._name = name
        self._files = files_dict
        self._is_dir = is_dir

    @property
    def name(self) -> str:
        """Return the name of this traversable."""
        return self._name

    def __str__(self) -> str:
        return self._name

    def is_dir(self) -> bool:
        """Check if this traversable represents a directory."""
        return self._is_dir

    def is_file(self) -> bool:
        """Check if this traversable represents a file."""
        return not self._is_dir and self._name in self._files

    def iterdir(self) -> Iterator[InMemoryTraversable]:
        """Iterate over the contents of this directory."""
        if not self.is_dir():
            raise NotADirectoryError(f"{self._name} is not a directory")

        # Get all files and subdirectories
        prefix = f"{self._name}/" if self._name else ""
        items = set()

        for file_path in self._files:
            if file_path.startswith(prefix):
                relative_path = file_path[len(prefix) :]
                if "/" in relative_path:
                    # This is in a subdirectory
                    subdir = relative_path.split("/")[0]
                    items.add((f"{prefix}{subdir}", True))  # subdirectory
                else:
                    # This is a direct file
                    items.add((file_path, False))  # file

        for item_path, is_dir in items:
            yield InMemoryTraversable(item_path, self._files, is_dir)

    def read_bytes(self) -> bytes:
        raise NotImplementedError("read_bytes is not implemented")

    def read_text(self, encoding: str = "utf-8") -> str:
        content = self._files[self._name]
        return content

    def __truediv__(self, child: str) -> InMemoryTraversable:
        """Navigate to a child path using the / operator."""
        if self.is_file():
            raise NotADirectoryError(f"{self._name} is not a directory")

        child_path = f"{self._name}/{child}" if self._name else child
        is_child_dir = any(path.startswith(f"{child_path}/") for path in self._files)

        return InMemoryTraversable(child_path, self._files, is_child_dir)

    def open(self, *args, **kwargs) -> io.IOBase:
        raise NotImplementedError("open is not implemented")

    def relative_to(self, other_path: str) -> str:
        # Normalize paths by removing trailing slashes
        self_path = self._name.rstrip("/")
        other_path = other_path.rstrip("/")

        if not other_path:
            return self_path

        if self_path == other_path:
            return ""
        elif self_path.startswith(other_path + "/"):
            return self_path[len(other_path) + 1 :]
        else:
            raise ValueError(f"'{self_path}' is not relative to '{other_path}'")


class InMemoryResourceReader(importlib.resources.abc.TraversableResources):
    """ResourceReader that works with in-memory files."""

    def __init__(self, files_dict: dict[str, str], package_name: str):
        """Initialize the resource reader with files dictionary and package name."""
        self._files = files_dict
        self._package_name = package_name

    def open_resource(self, *args, **kwargs) -> io.BytesIO:
        raise NotImplementedError("open_resource is not implemented")

    def resource_path(self, *args, **kwargs) -> str:
        raise NotImplementedError("resource_path is not implemented")

    def is_resource(self, *args, **kwargs) -> bool:
        raise NotImplementedError("is_resource is not implemented")

    def contents(self) -> Iterator[str]:
        raise NotImplementedError("contents is not implemented")

    def files(self) -> InMemoryTraversable:
        """Return a Traversable for the package."""
        return InMemoryTraversable(self._package_name, self._files, is_dir=True)


class ModelImporter(importlib.abc.MetaPathFinder):
    """A MetaPathFinder for dynamically loading OAREPO models."""

    def __init__(self, model: InvenioModel, namespace: SimpleNamespace):
        """Initialize the ModelImporter with a model and namespace."""
        self.model = model
        self.namespace = namespace

    def find_spec(
        self,
        fullname: str,
        path: Sequence[str] | None = None,  # noqa: ARG002 unused argument
        target: ModuleType | None = None,  # noqa: ARG002 unused argument
    ) -> importlib.machinery.ModuleSpec | None:
        """Find the specification for the model based on its name."""
        namespace = self.namespace
        if self._is_root_module_name(fullname):
            return self._make_root_module_spec(fullname, namespace)
        if self._is_submodule_name(fullname):
            return self._make_submodule_spec(fullname, namespace)

        return None  # Let other finders handle it

    def _is_root_module_name(self, fullname: str) -> bool:
        """Check if the module name is the root module of the model."""
        return fullname == f"runtime_models_{self.model.base_name}"

    def _is_submodule_name(self, fullname: str) -> bool:
        """Check if the module name is a submodule of the model."""
        return fullname.startswith(f"runtime_models_{self.model.base_name}.")

    def _make_root_module_spec(
        self,
        fullname: str,
        namespace: SimpleNamespace,
    ) -> importlib.machinery.ModuleSpec | None:
        class Loader(importlib.abc.Loader):
            def __init__(self, namespace: SimpleNamespace):
                self.namespace = namespace

            def create_module(
                self,
                spec: importlib.machinery.ModuleSpec,  # noqa: ARG002
            ) -> None:
                return None

            def exec_module(self, module: ModuleType) -> None:
                module.__dict__.update(namespace.__dict__)

            def get_resource_reader(
                self,
                name: str,
            ) -> importlib.resources.abc.ResourceReader:
                files_dict = getattr(self.namespace, "__files__", {})
                return InMemoryResourceReader(files_dict, "")

        return importlib.util.spec_from_loader(
            fullname,
            loader=Loader(namespace),
            is_package=True,
        )

    def _make_submodule_spec(
        self,
        fullname: str,
        namespace: SimpleNamespace,
    ) -> importlib.machinery.ModuleSpec | None:
        submodule = fullname[len(f"runtime_models_{self.model.base_name}.") :]
        submodule_root = submodule.split(".")[0]

        if hasattr(namespace, submodule_root):
            if not isinstance(getattr(namespace, submodule_root), SimpleNamespace):
                raise ImportError(
                    f"Expected a SimpleNamespace for {submodule_root}, "
                    f"but got {type(getattr(namespace, submodule_root))}",
                )

            class Loader(importlib.abc.Loader):
                def __init__(self, namespace: SimpleNamespace, fullname: str):
                    self.namespace = namespace
                    self.fullname = fullname

                def create_module(
                    self,
                    spec: importlib.machinery.ModuleSpec,  # noqa: ARG002
                ) -> None:
                    return None

                def exec_module(self, module: ModuleType) -> None:
                    module.__dict__.update(
                        getattr(namespace, submodule_root).__dict__,
                    )

                def get_resource_reader(
                    self,
                    name: str,
                ) -> importlib.resources.abc.ResourceReader:
                    name_parts = name.split(".")
                    if name_parts[0].startswith("runtime_models_"):
                        # not sure if should i even do this or just keep the full name
                        package_path = (
                            "/".join(name_parts[1:]) if len(name_parts) > 1 else ""
                        )
                    else:
                        package_path = "/".join(name_parts)

                    files_dict = getattr(self.namespace, "__files__", {})
                    return InMemoryResourceReader(files_dict, package_path)

        else:
            raise ImportError(
                f"Namespace 'runtime_models_{self.model.base_name}' does not contain '{submodule_root}'",
            )

        return importlib.util.spec_from_loader(
            fullname,
            loader=Loader(namespace, fullname),
            is_package=True,
        )

    def find_distributions(
        self,
        context: DistributionFinder.Context,
    ) -> list[Distribution]:
        """Find distributions.

        Return an iterable of all Distribution instances capable of
        loading the metadata for packages matching the ``context``,
        a DistributionFinder.Context instance.
        """
        if not context.name or context.name.lower().replace(
            "-",
            "_",
        ) == f"runtime_models_{self.model.name}".replace("-", "_"):
            return [ModelDistribution(self.model, self.namespace)]
        return []


def register_model(model: InvenioModel, namespace: SimpleNamespace) -> None:
    """Register the model importer to the meta path.

    This allows dynamic loading of the model based on its configuration.

    :param model: The model to register.
    :param namespace: The namespace associated with the model.
    """
    # prevent multiple registrations of the same model
    for importer in sys.meta_path:
        if isinstance(importer, ModelImporter) and importer.model == model:
            return

    # add the model importer to the meta path
    importer = ModelImporter(model, namespace)
    sys.meta_path.insert(0, importer)


def unregister_model(model: InvenioModel) -> None:
    """Unregister the model importer from the meta path.

    This allows cleanup of the model registration.

    :param model: The model to unregister.
    :param namespace: The namespace associated with the model.
    """
    for i, importer in enumerate(sys.meta_path):
        if isinstance(importer, ModelImporter) and importer.model == model:
            del sys.meta_path[i]
            return

    # If we reach here, the model was not registered
    raise ValueError(f"Model {model.name} is not registered.")
